server:
  port: 1993
  servlet:
    context-path: /excavator-admin
spring:
  thymeleaf:
    cache: false
  datasource:
    name: excavator-mysql-db
    username: glory
    password: 123456
    url: jdbc:mysql://vm1.glory.com:3306/excavator?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:
      auto-commit: true
      connection-timeout: 6000         # 链接超时
      minimum-idle: 2
      idle-timeout: 30000              # 空闲30s
      maximum-pool-size: 20
      max-lifetime: 120000             # 最大存活时间2分钟
      pool-name: 'mysql-conn-pool'
  redis:
    host: vm1.glory.com
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 2
        max-active: 10
        max-wait: 2000ms
