server:
  port: 1993
  servlet:
    context-path: /excavator-admin
spring:
  thymeleaf:
    cache: false
  datasource:
    name: excavator-mysql-db
    username: glory
    password: 123456
    url: jdbc:mysql://localhost:3306/excavator?useSSL=false&useUnicode=true&characterEncoding=utf-8
    hikari:
      auto-commit: true
      connection-timeout: 6000         # 链接超时
      minimum-idle: 2
      idle-timeout: 30000              # 空闲30s
      maximum-pool-size: 20
      max-lifetime: 120000             # 最大存活时间2分钟
      pool-name: 'mysql-conn-pool'
